
Pong: src/main.cpp
	g++ src/main.cpp src/glad.c src/Texture.cpp src/Shader.cpp src/Paddle.cpp src/Ball.cpp src/Window.cpp src/Game.cpp src/Input.cpp src/Renderer.cpp src/AudioEngine.cpp -Iinclude -I/usr/include/alsa -omain -lglfw -lasound
